### ISSUE TITLE
Emulationstation crash

### ISSUE THREAD

**Issue by wetriner** [HerbFargus/es-theme-pixel-meta#1]
I was checking out the new themes you've added and noticed that pixel-meta always crashed emulationstation for me on both Pi and Ubuntu. I've found the issue as far as I can tell (it doesn't crash after I change it). [This line](https://github.com/HerbFargus/es-theme-pixel-meta/blob/master/retropie/theme.xml#L134) appears to cause [this test](https://github.com/RetroPie/EmulationStation/blob/master/es-core/src/resources/Font.cpp#L198) to fail in emulationstation. It looks like fontSize doesn't like to be 0.

Cheers

**Comment by HerbFargus** [comment]
I see, thank you for testing. What size shall I make it?

**Comment by HerbFargus** [comment]
I guess it was rendered at 1 1 so the size is irrelevant but if there are overlaps I suppose we could just render it all transparent instead. Let me know if there are any other issues with it. Thanks
